config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  
  match '/signup' => 'users#new'
  
  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'
  match '/help' => 'pages#help'
  
  root :to => 'pages#home'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  # Virtual properties (don't exist in db)
  attr_accessor :password
  
  # Accessible properties
  attr_accessible :name, :email, :password, :password_confirmation
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length => { :maximum => 50 }
                    
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
                    
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => { :within => 6..40 }
                        
  before_save :encrypt_password
  
  # Return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    # Compare encrypted_password with the encrypted version of submitted_password
    encrypted_password == encrypt(submitted_password)
  end
  
  # Static/Class methods
  def self.authenticate(email, submitted_password)
    user = find_by_email email
    return nil if user.nil?
    return user if user.has_password? submitted_password
  end
  
  # Private functionality.
  # Anything after the 'private' pragma will be inaccessable from outside the class
  private
  
    def encrypt_password
      self.salt = make_salt if new_record? # Using ActiveRecord goodness to make sure this only gets created once.
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @title = 'Sign up'
  end
  
  def show
    @user = User.find params[:id]
    @title = @user.name
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user
    else
      @title = 'Sign up'
      @user.password = ''
      @user.password_confirmation = ''
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
# Modules are able to be included explicitly in Ruby apps.
# However, Rails includes modules under the helpsers/ folder
# to be availble in all views.

module ApplicationHelper
  
  # Return title on a per page basis                      # documentation comment
  def title                                               # method definition
    base_title = "Ruby on Rails Tutorial Sample App"      # variable assignment
    if @title.nil?                                        # boolean test for nil
      base_title                                          # implicit return
    else
      "#{base_title} | #{@title}"                         # string interpolation
    end
  end
  
  def logo
    image_tag("logo.png", :alt => 'Sample App', :class => 'round')
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag user.email,  :alt => user.name,
                                    :class => 'gravatar',
                                    :gravatar => options
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to 'About', about_path %></li>
			<li><%= link_to 'Contact', contact_path %></li>
			<li><a href="http://news.railstutorial.org">News</a></li>
			<li><a href="http://www.railstutorial.org">Rails Tutorial</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to 'Home', root_path %></li>
			<li><%= link_to 'Help', help_path %></li>
			<li><%= link_to 'Sign in', '#' %></li>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
<%= stylesheet_link_tag 'print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				<% flash.each do |key, value| %>
					<%= content_tag(:div, value, :class => "flash #{key}") %>
				<% end %>
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
 </html>

app/views/pages/about.html.erb
  <h1>Pages#about</h1>
  <p>Find me in app/views/pages/about.html.erb</p>
  

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>Get help on Ruby on Rails tutorial at the <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
	To get help on this sample app, see the <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>This is the home page for the <a href="http://railstutorial.org">Ruby on Rails Tutorial</a> sample application.</p>
<%= link_to 'Sign up now!', signup_path, :class => 'signup_button round' %>

app/views/pages/howdy.html.erb
<h1>Pages#howdy</h1>
<p>Find me in app/views/pages/howdy.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>	
		<% end %>
		</ul>
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tbody>
		<tr>
			<td class="main">
				<h1>
					<%= gravatar_for @user %>
					<%= @user.name %>
				</h1>
			</td>
			<td class="sidebar round">
				<strong>Name</strong> <%= @user.name %><br />
				<strong>URL</strong> <%= link_to user_path(@user), @user %>
			</td>
		</tr>
	</tbody>
</table>